### ISSUE TITLE
DecodeURIPath causes error since update to echo 4.1.16

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-go-core#31]
Probably caused by https://github.com/labstack/echo/pull/1535

```
echo: http: panic serving 127.0.0.1:53394: runtime error: index out of range [0] with length 0
goroutine 143 [running]:
net/http.(*conn).serve.func1(0xc0002594a0)
	/usr/local/Cellar/go/1.13.6/libexec/src/net/http/server.go:1767 +0x139
panic(0x4de80e0, 0xc00087a0a0)
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/panic.go:679 +0x1b2
github.com/labstack/echo/v4.(*context).Reset(0xc0002e4640, 0xc0000f8000, 0x50941e0, 0xc0001140e0)
	/Users/steven.vandervegt/projects/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/context.go:636 +0x2aa
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc00000c1e0, 0x50941e0, 0xc0001140e0, 0xc0000f8000)
	/Users/steven.vandervegt/projects/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/echo.go:604 +0x80
net/http.serverHandler.ServeHTTP(0xc000724000, 0x50941e0, 0xc0001140e0, 0xc0000f8000)
	/usr/local/Cellar/go/1.13.6/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0002594a0, 0x50995a0, 0xc0004ea980)
	/usr/local/Cellar/go/1.13.6/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.13.6/libexec/src/net/http/server.go:2928 +0x384
```

**Comment by stevenvegt** [comment]
https://github.com/labstack/echo/issues/1531#issuecomment-623474902
